- name: Setup WebServer
  hosts: web_server_group
  become: yes
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present
    - name: Start and Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

- name: Setup DbServer
  hosts: db_server_group
  become: yes
  tasks:
    - name: Install MySql Server
      yum:
        name: mariadb-server
        state: present
    - name: Start and Enable SQL MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

